Models/Pedidos.cs
using System;
using System.Collections.Generic;

namespace LojaVirtual.Models
{
	public class Pedidos
	{
		public Pedidos()
		{
			Itens = new List<PedidosItens>();
		}

		public int Id { get; set; }
		public int ClienteId { get; set; }
		public DateTime Data { get; set; }
		public Clientes Cliente { get; set; }
		public ICollection<PedidosItens> Itens { get; set; }
	}
}

Controllers/PedidosController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using LojaVirtual.Data;
using LojaVirtual.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace LojaVirtual.Controllers
{
	public class PedidosController : Controller
	{
		private readonly LojaVirtualContext _context;

		public PedidosController(LojaVirtualContext context)
		{
			_context = context;
		}

		// GET: Pedidos
		public async Task<IActionResult> Index()
		{
			var lojaVirtualContext = _context.Pedidos.Include(p => p.Cliente)
													 .Include(p => p.Itens).OrderBy( p=> p.Data)
																		   .OrderBy( p => p.Cliente.Nome);
			return View(await lojaVirtualContext.ToListAsync());
		}

		// GET: Pedidos/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var pedidos = await _context.Pedidos
				.Include(p => p.Cliente)
				.Include(p => p.Itens)
				.ThenInclude( i => i.Produto)
				.AsNoTracking()
				.FirstOrDefaultAsync(m => m.Id == id);


			if (pedidos == null)
			{
				return NotFound();
			}

			return View(pedidos);
		}

		public IActionResult IncluirItem(Pedidos pedido, int produtoId, int quantidade)
		{
			var produto = _context.Produtos.FirstOrDefault(p => p.Id == produtoId);

			if (produto != null)
			{
				pedido.Itens.Add(new PedidosItens
				{
					ProdutoId = produtoId,
					Quantidade = quantidade,
					Preco = produto.Preco,
					Total = produto.Preco * quantidade,
					Produto = produto
				});
			}

			return View(pedido);
		}

		// GET: Pedidos/Create
		public IActionResult Create()
		{
			ViewData["Clientes"] = new SelectList(_context.Clientes.OrderBy(c => c.Nome), "Id", "Nome");
			ViewData["Produtos"] = new SelectList(_context.Produtos.OrderBy(c => c.Descricao), "Id", "Descricao");
			return View();
		}

		// POST: Pedidos/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,ClienteId,Data")] Pedidos pedido)
		{
			if (ModelState.IsValid)
			{
				pedido.Data = DateTime.Now;

				_context.Add(pedido);

				await _context.SaveChangesAsync();

				return RedirectToAction(nameof(Details), "Pedidos", new { id = pedido.Id });
			}

			ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Nome", pedido.ClienteId);

			return View(pedido);
		}

		// GET: Pedidos/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var pedidos = await _context.Pedidos.FindAsync(id);
			if (pedidos == null)
			{
				return NotFound();
			}
			ViewData["ClienteId"] = new SelectList(_context.Clientes.OrderBy(c => c.Nome), "Id", "Nome", pedidos.ClienteId);
			return View(pedidos);
		}

		// POST: Pedidos/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,ClienteId,Data")] Pedidos pedidos)
		{
			if (id != pedidos.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(pedidos);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!PedidosExists(pedidos.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Id", pedidos.ClienteId);
			return View(pedidos);
		}

		// GET: Pedidos/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var pedidos = await _context.Pedidos
				.Include(p => p.Cliente)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (pedidos == null)
			{
				return NotFound();
			}

			return View(pedidos);
		}

		// POST: Pedidos/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var pedidos = await _context.Pedidos.FindAsync(id);
			_context.Pedidos.Remove(pedidos);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool PedidosExists(int id)
		{
			return _context.Pedidos.Any(e => e.Id == id);
		}
	}
}

Controllers/PedidosItensController.cs
using System.Linq;
using System.Threading.Tasks;
using LojaVirtual.Data;
using LojaVirtual.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace LojaVirtual.Controllers
{
	public class PedidosItensController : Controller
	{
		private readonly LojaVirtualContext _context;

		public PedidosItensController(LojaVirtualContext context)
		{
			_context = context;
		}

		// GET: PedidosItens
		public async Task<IActionResult> Index()
		{
			var lojaVirtualContext = _context.PedidosItens.Include(p => p.Pedido).Include(p => p.Produto);
			return View(await lojaVirtualContext.ToListAsync());
		}

		// GET: PedidosItens/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var pedidosItens = await _context.PedidosItens
				.Include(p => p.Pedido)
				.Include(p => p.Produto)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (pedidosItens == null)
			{
				return NotFound();
			}

			return View(pedidosItens);
		}

		// GET: PedidosItens/Create
		public IActionResult Create(int id)
		{
			var pedidosItens = new PedidosItens { PedidoId = id};

			ViewData["ProdutoId"] = new SelectList(_context.Produtos.OrderBy(o => o.Descricao), "Id", "Descricao");

			return View(pedidosItens);
		}

		// POST: PedidosItens/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("PedidoId,ProdutoId,NroItem,Preco,Quantidade,Total")] PedidosItens pedidosItens)
		{
			if (ModelState.IsValid)
			{
				_context.Add(pedidosItens);

				await _context.SaveChangesAsync();

				return RedirectToAction(nameof(Details), "Pedidos", new { id = pedidosItens.PedidoId });
			}

			ViewData["PedidoId"] = new SelectList(_context.Pedidos, "Id", "Id", pedidosItens.PedidoId);
			ViewData["ProdutoId"] = new SelectList(_context.Produtos, "Id", "Id", pedidosItens.ProdutoId);

			return View(pedidosItens);
		}

		// GET: PedidosItens/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var pedidosItens = await _context.PedidosItens.FirstOrDefaultAsync(m => m.Id == id);

			if (pedidosItens == null)
			{
				return NotFound();
			}

			ViewData["ProdutoId"] = new SelectList(_context.Produtos.OrderBy(o => o.Descricao), "Id", "Descricao");

			return View(pedidosItens);
		}

		// POST: PedidosItens/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,PedidoId,ProdutoId,NroItem,Preco,Quantidade,Total")] PedidosItens pedidosItens)
		{
			if (id != pedidosItens.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(pedidosItens);

					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!PedidosItensExists(pedidosItens.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}

				return RedirectToAction(nameof(Details), "Pedidos", new { id = pedidosItens.PedidoId });
			}

			ViewData["ProdutoId"] = new SelectList(_context.Produtos, "Id", "Nome", pedidosItens.ProdutoId);

			return View(pedidosItens);
		}

		// GET: PedidosItens/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var pedidosItens = await _context.PedidosItens
				.Include(p => p.Pedido)
				.Include(p => p.Produto)
				.FirstOrDefaultAsync(m => m.Id == id);

			if (pedidosItens == null)
			{
				return NotFound();
			}

			return View(pedidosItens);
		}

		// POST: PedidosItens/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var pedidosItens = await _context.PedidosItens.FindAsync(id);

			_context.PedidosItens.Remove(pedidosItens);

			await _context.SaveChangesAsync();

			return RedirectToAction(nameof(Details), "Pedidos", new { id = pedidosItens.PedidoId });
		}

		private bool PedidosItensExists(int id)
		{
			return _context.PedidosItens.Any(e => e.Id == id);
		}

		public decimal GetPreco(int produtoId)
		{
			var produto = _context.Produtos.Find(produtoId);

			return produto != null ? produto.Preco : 0;
		}
	}
}

Views/Pedidos/Create.cshtml
@model LojaVirtual.Models.Pedidos

@{
    ViewData["Title"] = "Novo Pedido";
}

@{
    var listItens = new List<LojaVirtual.Models.PedidosItens>();
}


<h1>@ViewData["Title"]</h1>

<h4>Pedidos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClienteId" class="control-label">Cliente</label>
                <select asp-for="ClienteId" class="form-control" asp-items="ViewBag.Clientes"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Continuar Pedido" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pedidos/Delete.cshtml
@model LojaVirtual.Models.Pedidos

@{
    ViewData["Title"] = "Delete";
}

<h1 class="btn btn-outline-danger">Excluir</h1>

<h3>Confirma a EXCLUSÃO do Pedido #@Model.Id?</h3>
<div>
    <h4>Pedidos</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cliente.Nome)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Excluir" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-secondary">Voltar</a>
    </form>
</div>

Views/Pedidos/Details - Copy.cshtml
@model LojaVirtual.Models.Pedidos

@{
    ViewData["Title"] = "Detalhes do Pedido";
}

<h1>@ViewData["Title"]</h1>

<div>
    <h4>Pedido #@Model.Id</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>

        <dt class="col-sm-2">
            Cliente:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cliente.Nome)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayName("Total:")
        </dt>
        <dd class="col-sm-10">
            @Model.Itens.Sum(i => i.Total).ToString("N2")
        </dd>
    </dl>
</div>

<partial name="_ViewItens" model="Model" />

<div>
    <a asp-action="Index">Voltar</a>
</div>

Views/Pedidos/Details.cshtml
@model LojaVirtual.Models.Pedidos

@{
    ViewData["Title"] = "Detalhes do Pedido";
}

<h1>@ViewData["Title"]</h1>

<div>
    <h4>Pedido #@Model.Id</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>

        <dt class="col-sm-2">
            Cliente:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cliente.Nome)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayName("Total:")
        </dt>
        <dd class="col-sm-10">
            @Model.Itens.Sum(i => i.Total).ToString("N2")
        </dd>
    </dl>

    <hr />

    <h4>Itens do Pedido</h4>

    <p>
        <a class="btn btn-primary" asp-controller="PedidosItens" asp-action="Create" asp-route-id="@Model.Id">Incluir Produto</a>
    </p>

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayName("Código")
                </th>
                <th>
                    @Html.DisplayName("Descrição")
                </th>
                <th class="number">
                    @Html.DisplayNameFor(model => model.Itens.FirstOrDefault().Quantidade)
                </th>
                <th class="number">
                    @Html.DisplayNameFor(model => model.Itens.FirstOrDefault().Preco)
                </th>
                <th class="number">
                    @Html.DisplayNameFor(model => model.Itens.FirstOrDefault().Total)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Itens)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Produto.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Produto.Descricao)
                    </td>
                    <td class="number">
                        @item.Quantidade.ToString("N2")
                    </td>
                    <td class="number">
                        @item.Preco.ToString("N2")
                    </td>
                    <td class="number">
                        @item.Total.ToString("N2")
                    </td>
                    <td>
                        <a asp-controller="PedidosItens" asp-action="Edit" asp-route-id="@item.Id" class=" btn btn-outline-success">Editar</a>
                        <a asp-controller="PedidosItens" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger">Excluir</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Voltar</a>
</div>

Views/Pedidos/Edit.cshtml
@model LojaVirtual.Models.Pedidos

@{
    ViewData["Title"] = "Editar";
}

<h1>@ViewData["Title"]</h1>

<h4>Pedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ClienteId" class="control-label">Cliente</label>
                <select asp-for="ClienteId" class="form-control" asp-items="ViewBag.ClienteId"></select>
                <span asp-validation-for="ClienteId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pedidos/Index.cshtml
@model IEnumerable<LojaVirtual.Models.Pedidos>

@{
    ViewData["Title"] = "Pedidos";
}

<h1>@ViewData["Title"]</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Novo Pedido</a>
</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th class="number">
                #
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data)
            </th>
            <th colspan="2">
                @Html.DisplayNameFor(model => model.Cliente)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.Cliente.Nome)
                </th>*@
            <th class="number">
                Valor
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="number">
                    <a asp-action="Details" asp-route-id="@item.Id">
                        @Html.DisplayFor(modelItem => item.Id)
                    </a>
                </td>
                <td>
                    @item.Data.ToShortDateString()
                </td>
                <td class="number">
                    @Html.DisplayFor(modelItem => item.Cliente.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cliente.Nome)
                </td>
                <td class="number">
                    @item.Itens.Sum(o => o.Total).ToString("N2")
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-success">Editar</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class=" btn btn-outline-info">Detalhes</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger">Excluir</a>
                </td>
            </tr>
        }
    </tbody>
</table>